controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\HomeController::login

login_process:
    path: /login_process
    controller: App\Controller\HomeController::loginProcess

register:
    path: /register
    controller: App\Controller\HomeController::register

register_process:
    path: /register_process
    controller: App\Controller\HomeController::registerProcess
